### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by tahmedge**
Added the first peer-reviewed ChatGPT evaluation paper [A Systematic Study and Comprehensive Evaluation of ChatGPT on Benchmark Datasets](https://arxiv.org/abs/2305.18486) accepted at [ACL 2023 Findings](https://2023.aclweb.org/program/accepted_findings/)

### CODE REVIEW

**Comment by jindongwang** [comment]
Thanks for your comment! We'll update the paper accordingly. You can expect to see a new version of the paper on Monday. @tahmedge

**Comment by tahmedge** [comment]
Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jindongwang** [comment]
@tahmedge We have also listed you in the acknowledgements section (https://github.com/MLGroupJLU/LLM-eval-survey#acknowledgements) for your help.

**Comment by tahmedge** [comment]
Thanks so much.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
